/* eslint-disable */
// GENERATED by scripts/generate-airtable-schema.ts — do not edit by hand.
// Base: apphPJFvk2oPNeJK9  Generated: 2026-09-28T20:14:11.752Z

export const BASE_ID = "apphPJFvk2oPNeJK9";

export interface AirtableAttachment {
  id?: string;
  url: string;
  filename: string;
  size?: number;
  type?: string;
  width?: number;
  height?: number;
  thumbnails?: Record<string, { url: string; width: number; height: number }>;
}

export interface FieldDef {
  /** Exact Airtable field name */
  name: string;
  /** camelCase key used in code */
  key: string;
  type: string;
  multiValue: boolean;
  computed: boolean;
  linkedTableId?: string;
  /** Field name on the linked table that links back here */
  inverseFieldName?: string;
}

export interface TableDef {
  id: string;
  name: string;
  exportName: string;
  fields: FieldDef[];
}

export interface ShxTeamRecordType {
  id: string;
  createdTime: string;
  /** Rep ID (formula) */
  repId?: string;
  /** Pro (multipleRecordLinks) */
  pro?: string[];
  /** Pro Name (singleSelect) */
  proName?: string;
  /** Badge ID (number) */
  badgeId?: number;
  /** Display Name (singleLineText) */
  displayName?: string;
  /** Preferred Full Name (multipleLookupValues) */
  preferredFullName?: string[];
  /** Job Title (multipleLookupValues) */
  jobTitle?: string[];
  /** Email (email) */
  email?: string;
  /** Work Email (multipleLookupValues) */
  workEmail?: string[];
  /** District (multipleLookupValues) */
  district?: string[];
  /** SHX City (multipleLookupValues) */
  shxCity?: string[];
  /** SHX State Abbreviation (formula) */
  shxStateAbbreviation?: string;
  /** SHX State (AI) (aiText) */
  shxStateAi?: string;
  /** SHX State (multipleLookupValues) */
  shxState?: string[];
  /** SHX Zip (multipleLookupValues) */
  shxZip?: string[];
  /** Role (singleSelect) */
  role?: string;
  /** Status (singleSelect) */
  status?: string;
  /** Offboard Pro (button) */
  offboardPro?: { label: string; url?: string };
  /** Revert Pro (button) */
  revertPro?: { label: string; url?: string };
  /** Reversion Date (dateTime) */
  reversionDate?: string;
  /** FORCE Reclaim (button) */
  forceReclaim?: { label: string; url?: string };
  /** Reclaim Leads (button) */
  reclaimLeads?: { label: string; url?: string };
  /** Load NEW CAP (button) */
  loadNewCap?: { label: string; url?: string };
  /** Load Leads (button) */
  loadLeads?: { label: string; url?: string };
  /** Skip Load Leads (checkbox) */
  skipLoadLeads?: boolean;
  /** Territory Override (multipleSelects) */
  territoryOverride?: string[];
  /** Radius (number) */
  radius?: number;
  /** Nearby Cities (aiText) */
  nearbyCities?: string;
  /** Nearby ZIPs (aiText) */
  nearbyZips?: string;
  /** Additional Cities (multilineText) */
  additionalCities?: string;
  /** Today's Leads (count) */
  todaysLeads?: number;
  /** # Assigned Active Leads (count) */
  assignedActiveLeads?: number;
  /** # Assigned Leads (count) */
  assignedLeads?: number;
  /** Daily New Lead Cap (number) */
  dailyNewLeadCap?: number;
  /** Active Lead Cap (number) */
  activeLeadCap?: number;
  /** Lead Interactions (multipleRecordLinks) */
  leadInteractions?: string[];
  /** # Interactions (count) */
  interactions?: number;
  /** Last Interaction Date (rollup) */
  lastInteractionDate?: string;
  /** Self-Gen Time (multipleRecordLinks) */
  selfGenTime?: string[];
  /** Running Comp Total (rollup) */
  runningCompTotal?: number;
  /** Assigned Leads (multipleRecordLinks) */
  assignedLeads1?: string[];
  /** Audit Log (multipleRecordLinks) */
  auditLog?: string[];
  /** Exports (multipleRecordLinks) */
  exports?: string[];
  /** Last Login (date) */
  lastLogin?: string;
  /** New Leads (count) */
  newLeads?: number;
  /** Leads Sold (count) */
  leadsSold?: number;
  /** Leads Installed (count) */
  leadsInstalled?: number;
  /** Leads Closed/No Sale (count) */
  leadsClosedNoSale?: number;
  /** Leads In-Progress | No Answer (count) */
  leadsInProgressNoAnswer?: number;
  /** Leads In-Progress | Follow-Up (count) */
  leadsInProgressFollowUp?: number;
  /** Leads In-Progress | Appt Set (count) */
  leadsInProgressApptSet?: number;
  /** Zone (multipleLookupValues) */
  zone?: string[];
  /** Director (multipleLookupValues) */
  director?: string[];
  /** Director Email (multipleLookupValues) */
  directorEmail?: string[];
  /** Senior Manager (multipleLookupValues) */
  seniorManager?: string[];
  /** Senior Manager Email (multipleLookupValues) */
  seniorManagerEmail?: string[];
  /** Manager (multipleLookupValues) */
  manager?: string[];
  /** Manager Email (multipleLookupValues) */
  managerEmail?: string[];
  /** Supervisor (multipleLookupValues) */
  supervisor?: string[];
  /** Supervisor Email (multipleLookupValues) */
  supervisorEmail?: string[];
  /** Reports To (multipleLookupValues) */
  reportsTo?: string[];
  /** Reports To Badge ID (multipleLookupValues) */
  reportsToBadgeId?: string[];
  /** Reports To Email (multipleLookupValues) */
  reportsToEmail?: string[];
  /** Admin Emails (email) */
  adminEmails?: string;
  /** Created (createdTime) */
  created?: string;
  /** SHX Record ID (formula) */
  shxRecordId?: string;
  /** Assigned Date (multipleLookupValues) */
  assignedDate?: string[];
  /** Today (formula) */
  today?: string;
}

export const ShxTeamTable: TableDef = {
  id: "tblUIvaqRrrBZE8y4",
  name: "SHX Team",
  exportName: "ShxTeam",
  fields: [
    { name: "Rep ID", key: "repId", type: "formula", multiValue: false, computed: true },
    { name: "Pro", key: "pro", type: "multipleRecordLinks", multiValue: true, computed: false, linkedTableId: "tbl2ys0w3ieacLEWJ", inverseFieldName: "SHX Team" },
    { name: "Pro Name", key: "proName", type: "singleSelect", multiValue: false, computed: false },
    { name: "Badge ID", key: "badgeId", type: "number", multiValue: false, computed: false },
    { name: "Display Name", key: "displayName", type: "singleLineText", multiValue: false, computed: false },
    { name: "Preferred Full Name", key: "preferredFullName", type: "multipleLookupValues", multiValue: true, computed: true },
    { name: "Job Title", key: "jobTitle", type: "multipleLookupValues", multiValue: true, computed: true },
    { name: "Email", key: "email", type: "email", multiValue: false, computed: false },
    { name: "Work Email", key: "workEmail", type: "multipleLookupValues", multiValue: true, computed: true },
    { name: "District", key: "district", type: "multipleLookupValues", multiValue: true, computed: true },
    { name: "SHX City", key: "shxCity", type: "multipleLookupValues", multiValue: true, computed: true },
    { name: "SHX State Abbreviation", key: "shxStateAbbreviation", type: "formula", multiValue: false, computed: true },
    { name: "SHX State (AI)", key: "shxStateAi", type: "aiText", multiValue: false, computed: true },
    { name: "SHX State", key: "shxState", type: "multipleLookupValues", multiValue: true, computed: true },
    { name: "SHX Zip", key: "shxZip", type: "multipleLookupValues", multiValue: true, computed: true },
    { name: "Role", key: "role", type: "singleSelect", multiValue: false, computed: false },
    { name: "Status", key: "status", type: "singleSelect", multiValue: false, computed: false },
    { name: "Offboard Pro", key: "offboardPro", type: "button", multiValue: false, computed: true },
    { name: "Revert Pro", key: "revertPro", type: "button", multiValue: false, computed: true },
    { name: "Reversion Date", key: "reversionDate", type: "dateTime", multiValue: false, computed: false },
    { name: "FORCE Reclaim", key: "forceReclaim", type: "button", multiValue: false, computed: true },
    { name: "Reclaim Leads", key: "reclaimLeads", type: "button", multiValue: false, computed: true },
    { name: "Load NEW CAP", key: "loadNewCap", type: "button", multiValue: false, computed: true },
    { name: "Load Leads", key: "loadLeads", type: "button", multiValue: false, computed: true },
    { name: "Skip Load Leads", key: "skipLoadLeads", type: "checkbox", multiValue: false, computed: false },
    { name: "Territory Override", key: "territoryOverride", type: "multipleSelects", multiValue: true, computed: false },
    { name: "Radius", key: "radius", type: "number", multiValue: false, computed: false },
    { name: "Nearby Cities", key: "nearbyCities", type: "aiText", multiValue: false, computed: true },
    { name: "Nearby ZIPs", key: "nearbyZips", type: "aiText", multiValue: false, computed: true },
    { name: "Additional Cities", key: "additionalCities", type: "multilineText", multiValue: false, computed: false },
    { name: "Today's Leads", key: "todaysLeads", type: "count", multiValue: false, computed: true },
    { name: "# Assigned Active Leads", key: "assignedActiveLeads", type: "count", multiValue: false, computed: true },
    { name: "# Assigned Leads", key: "assignedLeads", type: "count", multiValue: false, computed: true },
    { name: "Daily New Lead Cap", key: "dailyNewLeadCap", type: "number", multiValue: false, computed: false },
    { name: "Active Lead Cap", key: "activeLeadCap", type: "number", multiValue: false, computed: false },
    { name: "Lead Interactions", key: "leadInteractions", type: "multipleRecordLinks", multiValue: true, computed: false, linkedTableId: "tbl4SZBjhzZadr7ob", inverseFieldName: "Assigned Pro" },
    { name: "# Interactions", key: "interactions", type: "count", multiValue: false, computed: true },
    { name: "Last Interaction Date", key: "lastInteractionDate", type: "rollup", multiValue: false, computed: true },
    { name: "Self-Gen Time", key: "selfGenTime", type: "multipleRecordLinks", multiValue: true, computed: false, linkedTableId: "tblzC9UEWYumw6bMq", inverseFieldName: "SHX Pro" },
    { name: "Running Comp Total", key: "runningCompTotal", type: "rollup", multiValue: false, computed: true },
    { name: "Assigned Leads", key: "assignedLeads1", type: "multipleRecordLinks", multiValue: true, computed: false, linkedTableId: "tblm2jOl13AAWpvOy", inverseFieldName: "Assigned Pro" },
    { name: "Audit Log", key: "auditLog", type: "multipleRecordLinks", multiValue: true, computed: false, linkedTableId: "tblKJrRgC1lovXdSb", inverseFieldName: "Assigned Pro" },
    { name: "Exports", key: "exports", type: "multipleRecordLinks", multiValue: true, computed: false, linkedTableId: "tbleHHyf0puEcXTOr", inverseFieldName: "SHX" },
    { name: "Last Login", key: "lastLogin", type: "date", multiValue: false, computed: false },
    { name: "New Leads", key: "newLeads", type: "count", multiValue: false, computed: true },
    { name: "Leads Sold", key: "leadsSold", type: "count", multiValue: false, computed: true },
    { name: "Leads Installed", key: "leadsInstalled", type: "count", multiValue: false, computed: true },
    { name: "Leads Closed/No Sale", key: "leadsClosedNoSale", type: "count", multiValue: false, computed: true },
    { name: "Leads In-Progress | No Answer", key: "leadsInProgressNoAnswer", type: "count", multiValue: false, computed: true },
    { name: "Leads In-Progress | Follow-Up", key: "leadsInProgressFollowUp", type: "count", multiValue: false, computed: true },
    { name: "Leads In-Progress | Appt Set", key: "leadsInProgressApptSet", type: "count", multiValue: false, computed: true },
    { name: "Zone", key: "zone", type: "multipleLookupValues", multiValue: true, computed: true },
    { name: "Director", key: "director", type: "multipleLookupValues", multiValue: true, computed: true },
    { name: "Director Email", key: "directorEmail", type: "multipleLookupValues", multiValue: true, computed: true },
    { name: "Senior Manager", key: "seniorManager", type: "multipleLookupValues", multiValue: true, computed: true },
    { name: "Senior Manager Email", key: "seniorManagerEmail", type: "multipleLookupValues", multiValue: true, computed: true },
    { name: "Manager", key: "manager", type: "multipleLookupValues", multiValue: true, computed: true },
    { name: "Manager Email", key: "managerEmail", type: "multipleLookupValues", multiValue: true, computed: true },
    { name: "Supervisor", key: "supervisor", type: "multipleLookupValues", multiValue: true, computed: true },
    { name: "Supervisor Email", key: "supervisorEmail", type: "multipleLookupValues", multiValue: true, computed: true },
    { name: "Reports To", key: "reportsTo", type: "multipleLookupValues", multiValue: true, computed: true },
    { name: "Reports To Badge ID", key: "reportsToBadgeId", type: "multipleLookupValues", multiValue: true, computed: true },
    { name: "Reports To Email", key: "reportsToEmail", type: "multipleLookupValues", multiValue: true, computed: true },
    { name: "Admin Emails", key: "adminEmails", type: "email", multiValue: false, computed: false },
    { name: "Created", key: "created", type: "createdTime", multiValue: false, computed: true },
    { name: "SHX Record ID", key: "shxRecordId", type: "formula", multiValue: false, computed: true },
    { name: "Assigned Date", key: "assignedDate", type: "multipleLookupValues", multiValue: true, computed: true },
    { name: "Today", key: "today", type: "formula", multiValue: false, computed: true },
  ],
};

export interface NisLeadsRecordType {
  id: string;
  createdTime: string;
  /** Lead ID (formula) */
  leadId?: string;
  /** Status (singleSelect) */
  status?: string;
  /** Lead Type (singleSelect) */
  leadType?: string;
  /** Assignment Status (singleSelect) */
  assignmentStatus?: string;
  /** Reset Lead (button) */
  resetLead?: { label: string; url?: string };
  /** Assigned Pro (multipleRecordLinks) */
  assignedPro?: string[];
  /** # Assigned Active Leads (from Assigned Pro) (multipleLookupValues) */
  assignedActiveLeadsFromAssignedPro?: number[];
  /** Assigned Pro Email (multipleLookupValues) */
  assignedProEmail?: string[];
  /** Original Assigned Pro (singleLineText) */
  originalAssignedPro?: string;
  /** Date Assigned (date) */
  dateAssigned?: string;
  /** Opportunity Created (date) */
  opportunityCreated?: string;
  /** Opportunity Name (singleLineText) */
  opportunityName?: string;
  /** Opportunity ID (singleLineText) */
  opportunityId?: string;
  /** Service Name (singleLineText) */
  serviceName?: string;
  /** Sales Office (singleLineText) */
  salesOffice?: string;
  /** Customer District (singleSelect) */
  customerDistrict?: string;
  /** Customer Name (singleLineText) */
  customerName?: string;
  /** Customer Address Line 1 (singleLineText) */
  customerAddressLine1?: string;
  /** Customer Address Line 2 (singleLineText) */
  customerAddressLine2?: string;
  /** Customer City (singleLineText) */
  customerCity?: string;
  /** Customer State (singleLineText) */
  customerState?: string;
  /** Customer ZIP (AI) (number) */
  customerZipAi?: number;
  /** Customer Phone (phoneNumber) */
  customerPhone?: string;
  /** Customer Email (email) */
  customerEmail?: string;
  /** Display Address (aiText) */
  displayAddress?: string;
  /** Lead Details (multilineText) */
  leadDetails?: string;
  /** Total Interactions (count) */
  totalInteractions?: number;
  /** Last Interaction Date (rollup) */
  lastInteractionDate?: string;
  /** Days Since Last Interaction (formula) */
  daysSinceLastInteraction?: number;
  /** Notes/Interactions (multipleRecordLinks) */
  notesInteractions?: string[];
  /** Assignment Needed (checkbox) */
  assignmentNeeded?: boolean;
  /** Date Added (createdTime) */
  dateAdded?: string;
  /** Lead State (formula) */
  leadState?: string;
  /** Lead Source (singleSelect) */
  leadSource?: string;
  /** Pros Assigned (rollup) */
  prosAssigned?: number;
  /** Close Reason (richText) */
  closeReason?: string;
  /** Last Attempted (dateTime) */
  lastAttempted?: string;
  /** Customer ZIP (singleLineText) */
  customerZip?: string;
  /** Assigned Month (formula) */
  assignedMonth?: string;
}

export const NisLeadsTable: TableDef = {
  id: "tblm2jOl13AAWpvOy",
  name: "NIS Leads",
  exportName: "NisLeads",
  fields: [
    { name: "Lead ID", key: "leadId", type: "formula", multiValue: false, computed: true },
    { name: "Status", key: "status", type: "singleSelect", multiValue: false, computed: false },
    { name: "Lead Type", key: "leadType", type: "singleSelect", multiValue: false, computed: false },
    { name: "Assignment Status", key: "assignmentStatus", type: "singleSelect", multiValue: false, computed: false },
    { name: "Reset Lead", key: "resetLead", type: "button", multiValue: false, computed: true },
    { name: "Assigned Pro", key: "assignedPro", type: "multipleRecordLinks", multiValue: true, computed: false, linkedTableId: "tblUIvaqRrrBZE8y4", inverseFieldName: "Assigned Leads" },
    { name: "# Assigned Active Leads (from Assigned Pro)", key: "assignedActiveLeadsFromAssignedPro", type: "multipleLookupValues", multiValue: true, computed: true },
    { name: "Assigned Pro Email", key: "assignedProEmail", type: "multipleLookupValues", multiValue: true, computed: true },
    { name: "Original Assigned Pro", key: "originalAssignedPro", type: "singleLineText", multiValue: false, computed: false },
    { name: "Date Assigned", key: "dateAssigned", type: "date", multiValue: false, computed: false },
    { name: "Opportunity Created", key: "opportunityCreated", type: "date", multiValue: false, computed: false },
    { name: "Opportunity Name", key: "opportunityName", type: "singleLineText", multiValue: false, computed: false },
    { name: "Opportunity ID", key: "opportunityId", type: "singleLineText", multiValue: false, computed: false },
    { name: "Service Name", key: "serviceName", type: "singleLineText", multiValue: false, computed: false },
    { name: "Sales Office", key: "salesOffice", type: "singleLineText", multiValue: false, computed: false },
    { name: "Customer District", key: "customerDistrict", type: "singleSelect", multiValue: false, computed: false },
    { name: "Customer Name", key: "customerName", type: "singleLineText", multiValue: false, computed: false },
    { name: "Customer Address Line 1", key: "customerAddressLine1", type: "singleLineText", multiValue: false, computed: false },
    { name: "Customer Address Line 2", key: "customerAddressLine2", type: "singleLineText", multiValue: false, computed: false },
    { name: "Customer City", key: "customerCity", type: "singleLineText", multiValue: false, computed: false },
    { name: "Customer State", key: "customerState", type: "singleLineText", multiValue: false, computed: false },
    { name: "Customer ZIP (AI)", key: "customerZipAi", type: "number", multiValue: false, computed: false },
    { name: "Customer Phone", key: "customerPhone", type: "phoneNumber", multiValue: false, computed: false },
    { name: "Customer Email", key: "customerEmail", type: "email", multiValue: false, computed: false },
    { name: "Display Address", key: "displayAddress", type: "aiText", multiValue: false, computed: true },
    { name: "Lead Details", key: "leadDetails", type: "multilineText", multiValue: false, computed: false },
    { name: "Total Interactions", key: "totalInteractions", type: "count", multiValue: false, computed: true },
    { name: "Last Interaction Date", key: "lastInteractionDate", type: "rollup", multiValue: false, computed: true },
    { name: "Days Since Last Interaction", key: "daysSinceLastInteraction", type: "formula", multiValue: false, computed: true },
    { name: "Notes/Interactions", key: "notesInteractions", type: "multipleRecordLinks", multiValue: true, computed: false, linkedTableId: "tbl4SZBjhzZadr7ob", inverseFieldName: "Related Lead" },
    { name: "Assignment Needed", key: "assignmentNeeded", type: "checkbox", multiValue: false, computed: false },
    { name: "Date Added", key: "dateAdded", type: "createdTime", multiValue: false, computed: true },
    { name: "Lead State", key: "leadState", type: "formula", multiValue: false, computed: true },
    { name: "Lead Source", key: "leadSource", type: "singleSelect", multiValue: false, computed: false },
    { name: "Pros Assigned", key: "prosAssigned", type: "rollup", multiValue: false, computed: true },
    { name: "Close Reason", key: "closeReason", type: "richText", multiValue: false, computed: false },
    { name: "Last Attempted", key: "lastAttempted", type: "dateTime", multiValue: false, computed: false },
    { name: "Customer ZIP", key: "customerZip", type: "singleLineText", multiValue: false, computed: false },
    { name: "Assigned Month", key: "assignedMonth", type: "formula", multiValue: false, computed: true },
  ],
};

export interface ActivitiesRecordType {
  id: string;
  createdTime: string;
  /** Activity ID (formula) */
  activityId?: string;
  /** Related Lead (multipleRecordLinks) */
  relatedLead?: string[];
  /** Lead Name (multipleLookupValues) */
  leadName?: string[];
  /** Lead Status (multipleLookupValues) */
  leadStatus?: string[];
  /** Content (multilineText) */
  content?: string;
  /** Assigned Pro (from Related Lead) (multipleLookupValues) */
  assignedProFromRelatedLead?: string[];
  /** Assigned Pro (multipleRecordLinks) */
  assignedPro?: string[];
  /** Pro Email (multipleLookupValues) */
  proEmail?: string[];
  /** Date (date) */
  date?: string;
  /** Type (singleSelect) */
  type?: string;
  /** Follow-Up Date (date) */
  followUpDate?: string;
  /** Days Since Interaction (formula) */
  daysSinceInteraction?: number;
}

export const ActivitiesTable: TableDef = {
  id: "tbl4SZBjhzZadr7ob",
  name: "Activities",
  exportName: "Activities",
  fields: [
    { name: "Activity ID", key: "activityId", type: "formula", multiValue: false, computed: true },
    { name: "Related Lead", key: "relatedLead", type: "multipleRecordLinks", multiValue: true, computed: false, linkedTableId: "tblm2jOl13AAWpvOy", inverseFieldName: "Notes/Interactions" },
    { name: "Lead Name", key: "leadName", type: "multipleLookupValues", multiValue: true, computed: true },
    { name: "Lead Status", key: "leadStatus", type: "multipleLookupValues", multiValue: true, computed: true },
    { name: "Content", key: "content", type: "multilineText", multiValue: false, computed: false },
    { name: "Assigned Pro (from Related Lead)", key: "assignedProFromRelatedLead", type: "multipleLookupValues", multiValue: true, computed: true },
    { name: "Assigned Pro", key: "assignedPro", type: "multipleRecordLinks", multiValue: true, computed: false, linkedTableId: "tblUIvaqRrrBZE8y4", inverseFieldName: "Lead Interactions" },
    { name: "Pro Email", key: "proEmail", type: "multipleLookupValues", multiValue: true, computed: true },
    { name: "Date", key: "date", type: "date", multiValue: false, computed: false },
    { name: "Type", key: "type", type: "singleSelect", multiValue: false, computed: false },
    { name: "Follow-Up Date", key: "followUpDate", type: "date", multiValue: false, computed: false },
    { name: "Days Since Interaction", key: "daysSinceInteraction", type: "formula", multiValue: false, computed: true },
  ],
};

export interface ExportsRecordType {
  id: string;
  /** Badge ID (number) */
  badgeId?: number;
  /** Created Time (createdTime) */
  createdTime?: string;
  /** SHX (multipleRecordLinks) */
  shx?: string[];
  /** SHX Name (multipleLookupValues) */
  shxName?: string[];
  /** SHX Email (multipleLookupValues) */
  shxEmail?: string[];
  /** Customer Name (singleLineText) */
  customerName?: string;
  /** Compensation Details (richText) */
  compensationDetails?: string;
  /** SHX Compensation Total (currency) */
  shxCompensationTotal?: number;
}

export const ExportsTable: TableDef = {
  id: "tbleHHyf0puEcXTOr",
  name: "Exports",
  exportName: "Exports",
  fields: [
    { name: "Badge ID", key: "badgeId", type: "number", multiValue: false, computed: false },
    { name: "Created Time", key: "createdTime", type: "createdTime", multiValue: false, computed: true },
    { name: "SHX", key: "shx", type: "multipleRecordLinks", multiValue: true, computed: false, linkedTableId: "tblUIvaqRrrBZE8y4", inverseFieldName: "Exports" },
    { name: "SHX Name", key: "shxName", type: "multipleLookupValues", multiValue: true, computed: true },
    { name: "SHX Email", key: "shxEmail", type: "multipleLookupValues", multiValue: true, computed: true },
    { name: "Customer Name", key: "customerName", type: "singleLineText", multiValue: false, computed: false },
    { name: "Compensation Details", key: "compensationDetails", type: "richText", multiValue: false, computed: false },
    { name: "SHX Compensation Total", key: "shxCompensationTotal", type: "currency", multiValue: false, computed: false },
  ],
};

export interface AuditLogRecordType {
  id: string;
  createdTime: string;
  /** Audit ID (formula) */
  auditId?: string;
  /** Time Stamp (createdTime) */
  timeStamp?: string;
  /** Assigned Pro (multipleRecordLinks) */
  assignedPro?: string[];
  /** Actions (singleLineText) */
  actions?: string;
  /** Details (multilineText) */
  details?: string;
}

export const AuditLogTable: TableDef = {
  id: "tblKJrRgC1lovXdSb",
  name: "Audit Log",
  exportName: "AuditLog",
  fields: [
    { name: "Audit ID", key: "auditId", type: "formula", multiValue: false, computed: true },
    { name: "Time Stamp", key: "timeStamp", type: "createdTime", multiValue: false, computed: true },
    { name: "Assigned Pro", key: "assignedPro", type: "multipleRecordLinks", multiValue: true, computed: false, linkedTableId: "tblUIvaqRrrBZE8y4", inverseFieldName: "Audit Log" },
    { name: "Actions", key: "actions", type: "singleLineText", multiValue: false, computed: false },
    { name: "Details", key: "details", type: "multilineText", multiValue: false, computed: false },
  ],
};

export interface SelfGenTimeRecordType {
  id: string;
  createdTime: string;
  /** Self-Gen ID (formula) */
  selfGenId?: string;
  /** SHX Pro (multipleRecordLinks) */
  shxPro?: string[];
  /** SHX Pro Badge ID (multipleLookupValues) */
  shxProBadgeId?: number[];
  /** SHX Pro Email (multipleLookupValues) */
  shxProEmail?: string[];
  /** Date of Activity (dateTime) */
  dateOfActivity?: string;
  /** Time Slot (singleSelect) */
  timeSlot?: string;
  /** Activity Type (multipleSelects) */
  activityType?: string[];
  /** Completed? (checkbox) */
  completed?: boolean;
  /** Notes (multilineText) */
  notes?: string;
  /** Attachments (multipleAttachments) */
  attachments?: AirtableAttachment[];
  /** Date Created (createdTime) */
  dateCreated?: string;
}

export const SelfGenTimeTable: TableDef = {
  id: "tblzC9UEWYumw6bMq",
  name: "Self-Gen Time",
  exportName: "SelfGenTime",
  fields: [
    { name: "Self-Gen ID", key: "selfGenId", type: "formula", multiValue: false, computed: true },
    { name: "SHX Pro", key: "shxPro", type: "multipleRecordLinks", multiValue: true, computed: false, linkedTableId: "tblUIvaqRrrBZE8y4", inverseFieldName: "Self-Gen Time" },
    { name: "SHX Pro Badge ID", key: "shxProBadgeId", type: "multipleLookupValues", multiValue: true, computed: true },
    { name: "SHX Pro Email", key: "shxProEmail", type: "multipleLookupValues", multiValue: true, computed: true },
    { name: "Date of Activity", key: "dateOfActivity", type: "dateTime", multiValue: false, computed: false },
    { name: "Time Slot", key: "timeSlot", type: "singleSelect", multiValue: false, computed: false },
    { name: "Activity Type", key: "activityType", type: "multipleSelects", multiValue: true, computed: false },
    { name: "Completed?", key: "completed", type: "checkbox", multiValue: false, computed: false },
    { name: "Notes", key: "notes", type: "multilineText", multiValue: false, computed: false },
    { name: "Attachments", key: "attachments", type: "multipleAttachments", multiValue: true, computed: false },
    { name: "Date Created", key: "dateCreated", type: "createdTime", multiValue: false, computed: true },
  ],
};

export interface ControlPanelRecordType {
  id: string;
  createdTime: string;
  /** Name (singleLineText) */
  name?: string;
  /** Run Distribution (checkbox) */
  runDistribution?: boolean;
  /** Run Nearby Search (checkbox) */
  runNearbySearch?: boolean;
  /** Process New Uploads (checkbox) */
  processNewUploads?: boolean;
  /** Mark Lead Leftovers (checkbox) */
  markLeadLeftovers?: boolean;
  /** Unassigned Leads Count (number) */
  unassignedLeadsCount?: number;
  /** Raw Intake Count (number) */
  rawIntakeCount?: number;
}

export const ControlPanelTable: TableDef = {
  id: "tbldoEQ03ydWiBJC7",
  name: "Control Panel",
  exportName: "ControlPanel",
  fields: [
    { name: "Name", key: "name", type: "singleLineText", multiValue: false, computed: false },
    { name: "Run Distribution", key: "runDistribution", type: "checkbox", multiValue: false, computed: false },
    { name: "Run Nearby Search", key: "runNearbySearch", type: "checkbox", multiValue: false, computed: false },
    { name: "Process New Uploads", key: "processNewUploads", type: "checkbox", multiValue: false, computed: false },
    { name: "Mark Lead Leftovers", key: "markLeadLeftovers", type: "checkbox", multiValue: false, computed: false },
    { name: "Unassigned Leads Count", key: "unassignedLeadsCount", type: "number", multiValue: false, computed: false },
    { name: "Raw Intake Count", key: "rawIntakeCount", type: "number", multiValue: false, computed: false },
  ],
};

export const ALL_TABLES: TableDef[] = [ShxTeamTable, NisLeadsTable, ActivitiesTable, ExportsTable, AuditLogTable, SelfGenTimeTable, ControlPanelTable];
