/**
 * Pulls the live base schema from the Airtable Metadata API and writes
 * server/airtable/schema.generated.ts: table/field definitions plus TypeScript
 * record types, using the same camelCase key convention the old Zite layer used
 * (so every `record.someKey` in the endpoints keeps working).
 *
 *   AIRTABLE_API_KEY=pat... AIRTABLE_BASE_ID=app... npm run schema:generate
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const API_KEY = process.env.AIRTABLE_API_KEY;
const BASE_ID = process.env.AIRTABLE_BASE_ID || 'apphPJFvk2oPNeJK9';
if (!API_KEY) {
  console.error('AIRTABLE_API_KEY is required');
  process.exit(1);
}

// Only the tables the app touches. Add a table here if an endpoint needs it.
const TABLES = ['SHX Team', 'NIS Leads', 'Activities', 'Exports', 'Audit Log', 'Self-Gen Time', 'Control Panel'];

type MetaField = {
  id: string;
  name: string;
  type: string;
  options?: any;
};
type MetaTable = { id: string; name: string; primaryFieldId: string; fields: MetaField[] };

/** "Today's Leads" -> todaysLeads, "# Assigned Leads" -> assignedLeads, "Customer ZIP (AI)" -> customerZipAi */
function toCamel(name: string): string {
  const words = name.replace(/['’]/g, '').split(/[^A-Za-z0-9]+/).filter(Boolean);
  if (words.length === 0) return 'field';
  const out = words
    .map((w, i) => {
      const lower = w.toLowerCase();
      return i === 0 ? lower : lower.charAt(0).toUpperCase() + lower.slice(1);
    })
    .join('');
  return /^[0-9]/.test(out) ? `_${out}` : out;
}

/** "SHX Team" -> ShxTeam */
function toPascal(name: string): string {
  const c = toCamel(name);
  return c.charAt(0).toUpperCase() + c.slice(1);
}

function resultTsType(result: any): string {
  if (!result) return 'any';
  switch (result.type) {
    case 'number':
    case 'currency':
    case 'percent':
    case 'count':
    case 'rating':
    case 'duration':
    case 'autoNumber':
      return 'number';
    case 'checkbox':
      return 'boolean';
    default:
      return 'string';
  }
}

function tsTypeFor(f: MetaField): string {
  switch (f.type) {
    case 'singleLineText':
    case 'multilineText':
    case 'richText':
    case 'email':
    case 'phoneNumber':
    case 'url':
    case 'singleSelect':
    case 'aiText':
    case 'date':
    case 'dateTime':
    case 'createdTime':
    case 'lastModifiedTime':
    case 'barcode':
      return 'string';
    case 'number':
    case 'currency':
    case 'percent':
    case 'count':
    case 'rating':
    case 'duration':
    case 'autoNumber':
      return 'number';
    case 'checkbox':
      return 'boolean';
    case 'multipleSelects':
    case 'multipleRecordLinks':
      return 'string[]';
    case 'multipleAttachments':
      return 'AirtableAttachment[]';
    case 'multipleLookupValues':
    case 'rollup': {
      const t = resultTsType(f.options?.result);
      return f.type === 'rollup' ? t : `${t}[]`;
    }
    case 'formula':
      return resultTsType(f.options?.result);
    case 'button':
      return '{ label: string; url?: string }';
    case 'singleCollaborator':
    case 'createdBy':
    case 'lastModifiedBy':
      return '{ id: string; email?: string; name?: string }';
    default:
      return 'any';
  }
}

const MULTI_VALUE = new Set(['multipleSelects', 'multipleRecordLinks', 'multipleLookupValues', 'multipleAttachments']);
const COMPUTED = new Set(['formula', 'rollup', 'count', 'lookup', 'multipleLookupValues', 'createdTime', 'lastModifiedTime', 'autoNumber', 'button', 'createdBy', 'lastModifiedBy', 'aiText']);

async function main() {
  const res = await fetch(`https://api.airtable.com/v0/meta/bases/${BASE_ID}/tables`, {
    headers: { Authorization: `Bearer ${API_KEY}` },
  });
  if (!res.ok) throw new Error(`Airtable meta API ${res.status}: ${await res.text()}`);
  const { tables } = (await res.json()) as { tables: MetaTable[] };
  const byId = new Map(tables.map(t => [t.id, t]));

  const chosen = TABLES.map(name => {
    const t = tables.find(x => x.name === name);
    if (!t) throw new Error(`Table "${name}" not found in base ${BASE_ID}`);
    return t;
  });

  let out = `/* eslint-disable */\n// GENERATED by scripts/generate-airtable-schema.ts — do not edit by hand.\n// Base: ${BASE_ID}  Generated: ${new Date().toISOString()}\n\n`;
  out += `export const BASE_ID = ${JSON.stringify(BASE_ID)};\n\n`;
  out += `export interface AirtableAttachment {\n  id?: string;\n  url: string;\n  filename: string;\n  size?: number;\n  type?: string;\n  width?: number;\n  height?: number;\n  thumbnails?: Record<string, { url: string; width: number; height: number }>;\n}\n\n`;
  out += `export interface FieldDef {\n  /** Exact Airtable field name */\n  name: string;\n  /** camelCase key used in code */\n  key: string;\n  type: string;\n  multiValue: boolean;\n  computed: boolean;\n  linkedTableId?: string;\n  /** Field name on the linked table that links back here */\n  inverseFieldName?: string;\n}\n\n`;
  out += `export interface TableDef {\n  id: string;\n  name: string;\n  exportName: string;\n  fields: FieldDef[];\n}\n\n`;

  const tableEntries: string[] = [];
  for (const t of chosen) {
    // `id` is reserved for the record id; a field literally named "ID" becomes id1.
    const seen = new Map<string, number>([['id', 1]]);
    const fields = t.fields.map(f => {
      let key = toCamel(f.name);
      const n = seen.get(key) ?? 0;
      seen.set(key, n + 1);
      if (n > 0) key = `${key}${n}`; // Zite-style dedupe: assignedLeads, assignedLeads1
      let linkedTableId: string | undefined;
      let inverseFieldName: string | undefined;
      if (f.type === 'multipleRecordLinks') {
        linkedTableId = f.options?.linkedTableId;
        const lt = linkedTableId ? byId.get(linkedTableId) : undefined;
        inverseFieldName = lt?.fields.find(x => x.id === f.options?.inverseLinkFieldId)?.name;
      }
      return { name: f.name, key, type: f.type, multiValue: MULTI_VALUE.has(f.type), computed: COMPUTED.has(f.type), linkedTableId, inverseFieldName, ts: tsTypeFor(f) };
    });

    const pascal = toPascal(t.name);
    // Every record carries Airtable's createdTime unless the table has its own "Created Time" field.
    const hasCreatedTimeField = fields.some(f => f.key === 'createdTime');
    out += `export interface ${pascal}RecordType {\n  id: string;\n${hasCreatedTimeField ? '' : '  createdTime: string;\n'}`;
    for (const f of fields) out += `  /** ${f.name} (${f.type}) */\n  ${f.key}?: ${f.ts};\n`;
    out += `}\n\n`;

    out += `export const ${pascal}Table: TableDef = {\n  id: ${JSON.stringify(t.id)},\n  name: ${JSON.stringify(t.name)},\n  exportName: ${JSON.stringify(pascal)},\n  fields: [\n`;
    for (const f of fields) {
      const parts = [`name: ${JSON.stringify(f.name)}`, `key: ${JSON.stringify(f.key)}`, `type: ${JSON.stringify(f.type)}`, `multiValue: ${f.multiValue}`, `computed: ${f.computed}`];
      if (f.linkedTableId) parts.push(`linkedTableId: ${JSON.stringify(f.linkedTableId)}`);
      if (f.inverseFieldName) parts.push(`inverseFieldName: ${JSON.stringify(f.inverseFieldName)}`);
      out += `    { ${parts.join(', ')} },\n`;
    }
    out += `  ],\n};\n\n`;
    tableEntries.push(`${pascal}Table`);
  }

  out += `export const ALL_TABLES: TableDef[] = [${tableEntries.join(', ')}];\n`;

  const target = resolve(process.cwd(), 'server/airtable/schema.generated.ts');
  writeFileSync(target, out);
  console.log(`Wrote ${target} (${chosen.length} tables)`);
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
